title = "ABlog"
port = ":3002"

[admin]
name = "arnold"
passwd = "hgx1234"
bio = "hahaha"

[database]
server = "127.0.0.1"
ports = [ 3306 ]
dbname = "ablog_db"
dbuser = "ablog"
dbpasswd = "ablog"
connection_max = 5000
enabled = true